### ISSUE TITLE
Problem with "empty" control

### ISSUE THREAD

**Issue by Triangle333** [ChrisMayor/D365RichTextEditor#5] opened 2020-04-21 08:44 UTC
Given: A field on a form with attached D365RichTextEditor control.

a) Open fresh form and inspect this field value: Xrm.Page.getAttribute( "fieldName").getValue() will return **null**. So far, so good
b) Enter some text into control and then remove all text. Value returned will be `"<p><br></p>"`. Expected value is **null**
c) Enter some spaces into control and save. Refresh form (F5) and control will stop showing these spaces but value returned will be still `"<p>    </p>"`. Expected value is **null** because built-in controls trim strings on save. I think that text consisting of only spaces and new lines should be treated (and saved) as null too.

Why this is important: I have some validation logic on form that checks if certain fields are filled or not. With built-in controls this is easy, just compare with null. But now we have new unexpected states of data. Can you please make this control to be more compliant with system`s way of saving strings?

**Comment by ChrisMayor** [comment] 2020-04-22 14:24
Hello,
I will have a look at this in the next days.

**Comment by ChrisMayor** [comment] 2020-04-25 13:19
Hello,
I fixed the issue with v2.1 and the control will now return null if no text is entered.

Please update your solution to the current version v2.1

**Comment by Triangle333** [comment] 2020-04-27 07:20
Thank you for prompt reaction.

Item c) is still actual. Built-in multi-line controls will save spaces as is, but if field is mandatory and contains only spaces and new lines, system will treat it as empty and will not allow saving. This is proper behavior.

With D365RichTextEditor mandatory field with such content will also contain tags and system will allow saving it as if it's a meaningful data. Can you please make control return null instead?

**Comment by ChrisMayor** [comment] 2020-04-27 09:08
Hallo Triangle333,

I will fix c) aswell as soon I got some time in the next days.

**Comment by ChrisMayor** [comment] 2020-05-01 09:16
Hallo Triangle333,

the issue is fixed now, please upgrade to V2.4.

Empty strings mixed with html, not mixed with html and in any length are handled as NULL now,

**Closed as completed by ChrisMayor** 2020-05-01 09:16 UTC
Labels: bug

**Comment by Triangle333** [comment] 2020-05-04 08:15
Thanx! Our Q&A is quite happy now :)
